[project]
name = "monolith"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Marko Elez", email = "markoelez7@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jax",
    "flax",
    "optax",
    "scikit-learn>=1.8.0",
]
